language: java
jdk:
  - openjdk8
env:
  - NODE_VERSION="10.0.0"
install:
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - npm install
script: 
  - node fuse build:dist
after_success:
  - echo Build success
after_failure:
  - echo Build failure